export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    DEFAULT: '/',
    USERS:'users',
    INVENTORY: 'inventory',
    BENEFICIARIES: 'beneficiaries',
    BEN_LIST: 'ben_list',
    ACTIVITIES_LIST: 'activities-list',
    ACTIVITIES: 'activities',
    ROLES: 'roles',
    PERMISSIONS: 'permissions',
    UNAUTHORIZED: 'unauthorized',
    ASSISTANCE: 'assistance',
    RATINGS: 'ratings',
    ASSOCIATIONS: "associations",
}
