export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    DEFAULT: '/',
    USERS:'users',
    INVENTORY: 'inventory',
    BENEFICIARIES: 'beneficiaries',
    BEN_LIST: 'ben_list',
    ACTIVITIES_LIST: 'activities-list',
    WINERIES_LIST: 'wineries-list',
    WINERIES: 'wineries',
    ACTIVITIES: 'activities',
    ROLES: 'roles',
    PERMISSIONS: 'permissions',
    UNAUTHORIZED: 'unauthorized',
    ASSISTANCE: 'assistance',
    WORKSHOP: 'workshop-list',
    RATINGS: 'ratings',
    RATING_LIST: 'rating-list',
    ASSOCIATIONS: "associations",
    REPRESENTATIVES: "representantives",
}
