export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    DEFAULT: '/',
    USERS:'users',
    INVENTORY: 'inventory',
    BENEFICIARIES: 'beneficiaries',
    BEN_LIST: 'ben_list',
    ACTIVITIES_LIST: 'activities-list',
    WINERIES_LIST: 'wineries-list',
    WINERIES: 'wineries',
    ACTIVITIES: 'activities',
    ROLES: 'roles',
    PERMISSIONS: 'permissions',
    UNAUTHORIZED: 'unauthorized',
    ASSISTANCE: 'assistance',
    WORKSHOP: 'workshop-list',
    RATINGS: 'ratings',
    RATING_LIST: 'rating-list',
    ASSOCIATIONS: "associations",
    REPRESENTATIVES: "representantives",
    DELIVERY_LIST: "delivery-list",
    PHYSICAL_DELIVERY_LIST: "physical-delivery-list",
    PHYSICAL_DELIVERY: "physical-delivery",
    DELIVERY: "delivery",
    EVENTS_LIST: 'events-list',
    EVENTS_ASSISTANCE: 'events-assistance',
    EVENTS: 'events',
    STATS: 'stats',
    REPRESENTATIVE_DELIVERY_LIST: 'rep-delivery-list',
    REPRESENTATIVE_DELIVERY_DETAIL: 'rep-delivery-detail',
    REPORTS: 'reports',
    RESUMEN: 'resumen',
    ACTS: 'acts'

}
